### PR TITLE
DTSAM-427: FTAs for ST Judicial Appointments

### PR DESCRIPTION
**Pull request by SivaKanukolluQA**
### Jira link
https://tools.hmcts.net/jira/browse/DTSAM-427

### Change description
Adding FTAs for ST Judicial appointments

> NB: this PR is branched from: #2095

### Testing done
This is Automation Testing ticket itself.

### Checklist
- [ ] Does this PR introduce a breaking change - no

### CODE REVIEW

**Review by mikebrownccd — APPROVED** [review]
LGTM

**Review by abul-syed — DISMISSED** [review]
lgtm

**Review by mattnayler — APPROVED** [review]
LGTM

**Review by mattnayler — APPROVED** [review]
Re-reviewed after branch change

**Review by mikebrownccd — APPROVED** [review]
LGTM

**Pull request merged**
