### PR TITLE
Dtsam 353 civil wa emp judge appt

### PR DESCRIPTION
**Pull request by abul-syed**
### Jira link (if applicable)

https://tools.hmcts.net/jira/browse/DTSAM-353

### Change description ###

(Civil) Add Employment Judge to Civil work allocation ORM config

### CODE REVIEW

**Review by mikebrownccd — APPROVED** [review]
LGTM

**Review by mattnayler — APPROVED** [review]
LGTM:  I have added one comment relating to an inherrited unit test issue: which given your welcome expansion of tests to cover all CIVIL flags it would feel even more complete if we expanded JOH test sto cover all JOH scenarios.

**Review by mikebrownccd — APPROVED** [review]
LGTM

**Review by mattnayler — APPROVED** [review]
LGTM

**Pull request merged**
