### PR TITLE
AM-2891: Add @WithSpan annotation to JRD & CRD topic consumers

### PR DESCRIPTION
**Pull request by tomxelliott**
### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/AM-2891

### Change description ###
Add @WithSpan annotation to JRD & CRD topic consumers

### CODE REVIEW

**Review by mattnayler — DISMISSED** [review]
LGTM

**Review by mikebrownccd — APPROVED** [review]
LGTM

**Review by prashanthkumarnb — APPROVED** [review]

**Review by mikebrownccd — APPROVED** [review]
LGTM

**Review by mattnayler — APPROVED** [review]
Re-approved after 23dd739a97ac201acffd6bbbcee7ad0bae40ecf2.

**Pull request merged**
